#!/usr/bin/env sh
#
# webdown -- static website generator from markdown sources
#          .    .
# .    , _ |_  _| _ .    ,._
#  \/\/ (/,[_)(_](_) \/\/ [ )
#
# Copyright (C) 2012-2013 Juan M Martínez
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See http://sam.zoy.org/wtfpl/COPYING for more
# details.
#
# History
# -------
# 2012/04/09: v0.2
#  * Remove title and title-separator
# 2012/03/22: First version
#

VERSION=0.2
QUIET=0
LAYOUT=

if [[ ! -x /usr/bin/sundown ]]; then
	echo "Please install 'sundown' to use ${0##*/}"
	exit 1
fi

version()
{
	echo "${0##*/} v$VERSION"
}

usage()
{
	cat << EOF
usage: ${0##*/} [options] <source> <destination>

options:
  -l, --layout <file>                  Layout for each generated page
  -q, --quiet                          Do not display any message
  -h, --help                           Display this message
  -V, --version                        Print version and exit
EOF
}

log()
{
	local msg=$1; shift
	if [[ 0 == $QUIET ]]; then
		echo "$msg" "$@"
	fi
}

fatal()
{
	local msg=$1; shift
	log "$msg" "$@" >&2
	exit 1
}

SHORT_OPTS="qhVl:"
LONG_OPTS="quiet,help,version,layout:"

argv=$(getopt -l "$LONG_OPTS" -- "$SHORT_OPTS" "$@") || { usage ; exit 1 ; }
eval set -- "$argv"

while true ; do
	case "$1" in
		-l|--layout)             LAYOUT="$2" ; shift 2 ;;

		-q|--quiet)              QUIET=1 ; shift ;;
		-h|--help)               usage ; exit ;;
		-V|--version)            version ; exit ;;

		--)                      shift ; break ;;
		*)                       usage ; exit 1 ;;
	esac
done

[[ $# -eq 2 ]] || { usage ; exit 1 ; }

SRC=$(readlink -f $1)
DST=$(readlink -f $2)

[[ -d "$SRC" ]] || { fatal "Invalid source directory" ; }
[[ -d "$DST" ]] || { fatal "Invalid destination directory" ; }

if [[ -f "$LAYOUT" ]]; then
	LCONTENT=$(cat $LAYOUT)

	if [[ ! "$LCONTENT" =~ "{{ CONTENT }}" ]]; then
		fatal "The layout file must contain a \"{{ CONTENT }}\" variable"
	fi
fi

for SFILE in $(find "$SRC" -name '*.markdown' -type f); do
	DFILE=${SFILE/$SRC/$DST}
	DFILE=${DFILE/%markdown/html}

	mkdir -p $(dirname $DFILE)

	if [[ -n "$LCONTENT" ]]; then
		MARKDOWN=$(sundown $SFILE)
		CTITLE=$(head -n1 "$SFILE")

		CONTENT=$LCONTENT
		CONTENT=${CONTENT/\{\{ CONTENT \}\}/$MARKDOWN}
		CONTENT=${CONTENT/\{\{ TITLE \}\}/$CTITLE}
	else
		CONTENT=$(sundown $SFILE)
	fi

	echo "$CONTENT" > $DFILE
done

# End of file
# vim: set ts=2 sw=2 noet:
