#!/usr/bin/env sh
#
# webdown -- static website generator from markdown sources
#
# Copyright (C) 2012 Juan M Martínez
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See http://sam.zoy.org/wtfpl/COPYING for more
# details.
#
# Hisotry
# -------
# 2012/03/22: First version
#

VERSION=0.1
LAYOUT=
TITLE=
TITLE_SEPARATOR="|"

if [[ ! -x /usr/bin/sundown ]]; then
	echo "Please install 'sundown' to use ${0##*/}"
	exit 1
fi

version()
{
	echo "${0##*/} v$VERSION"
}

usage()
{
	cat << EOF
usage: ${0##*/} [options] <source> <destination>

options:
  -l, --layout <file>                  Layout for each generated page
  -t, --title <title>                  Page title
      --title-separator <separator>    Title separator
  -h, --help                           Display this message
  -V, --version                        Print version and exit
EOF
}

LONG_OPTS="help,version,layout:,title:,title-separator:"

argv=$(getopt -l "$LONG_OPTS" -- 'hVl:t:' "$@") || { usage ; exit 1 ; }
eval set -- "$argv"

while true ; do
	case "$1" in
		-l|--layout)             LAYOUT="$2" ; shift 2 ;;
		-t|--title)              TITLE="$2" ; shift 2 ;;
		   --title-separator)    TITLE_SEPARATOR="$2" ; shift 2 ;;

		-h|--help)               usage ; exit ;;
		-V|--version)            version ; exit ;;

		--)                      shift ; break ;;
		*)                       usage ; exit 1 ;;
	esac
done

[[ $# -eq 2 ]] || { usage ; exit 1 ; }

SRC=$(readlink -f $1)
DST=$(readlink -f $2)

[[ -d "$SRC" ]] || { echo "Invalid source directory" ; exit 1 ; }
[[ -d "$DST" ]] || { echo "Invalid destination directory" ; exit 1 ; }

if [[ -f "$LAYOUT" ]]; then
	LCONTENT=$(cat $LAYOUT)

	if [[ ! "$LCONTENT" =~ "{{ CONTENT }}" ]]; then
		echo "The layout file must contain a \"{{ CONTENT }}\" variable"
		exit 1
	fi
fi

for SFILE in $(find "$SRC" -name '*.markdown' -type f); do
	DFILE=${SFILE/$SRC/$DST}
	DFILE=${DFILE/%markdown/html}

	mkdir -p $(dirname $DFILE)

	if [[ -n "$LCONTENT" ]]; then
		MARKDOWN=$(sundown $SFILE)

		CONTENT=$LCONTENT
		CONTENT=${CONTENT/\{\{ CONTENT \}\}/$MARKDOWN}

		CTITLE=$(head -n1 "$SFILE")

		if [[ (-n "$TITLE") && ("$CTITLE" != "$TITLE") ]]; then
			CTITLE="$CTITLE $TITLE_SEPARATOR $TITLE"
		fi

		CONTENT=${CONTENT/\{\{ TITLE \}\}/$CTITLE}
	else
		CONTENT=$(sundown $SFILE)
	fi

	echo "$CONTENT" > $DFILE
done

# End of file
# vim: set ts=2 sw=2 noet:
