.TH "webdown" "1" "April 2012" "webdown" "User Commands"

.SH "NAME"
webdown \- static website generator from markdown sources

.SH "SYNOPSIS"
\&\fBwebdown [\fIoptions\fB] \fIsource destination\fR

.SH "DESCRIPTION"
Creates HTML files into the \fIdestination\fR directory from the markdown
files in the \fIsource\fR directory.

.SH "OPTIONS"
.IP "\fB-l, --layout \fIfile\fR"
Use the HTML \fIfile\fR as layout. The current variables will be replaced:

  \fB{{ CONTENT }}\fR - The HTML of the markdown convertion
  \fB{{ TITLE }}\fR   - The page title

.IP "\fB-q, --quiet\fR"
Do not print any message.

.IP "\fB-h, --help\fR"
Prints the synopsis and list the options.

.IP "\fB-v, --version\fR"
Prints the \fIwebdown\fR(1) version and exit.

.SH "AUTHOR"
Juan M Martínez <jm@guide42.com>

.SH "SEE ALSO"
\fBsundown\fR (https://github.com/tanoku/sundown)
